name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Ex15 (os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04-arm"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: setup-miniconda
        continue-on-error: true
        with:
          miniforge-version: latest
      - name: Check ARM
        shell: bash -el {0}
        run: |
          conda install -y python
          python -c "import platform; assert platform.machine() == 'aarch64', platform.machine()"
      
      - name: build
        run: |
          # (Recommended) Create a new conda environment
          conda create -n bitnet-cpp python=3.9
          conda activate bitnet-cpp
          pip install -r requirements.txt
          # Manually download the model and run with local path
          huggingface-cli download microsoft/BitNet-b1.58-2B-4T-gguf --local-dir models/BitNet-b1.58-2B-4T
          python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s
